
services:

  emshop-mysql:
    image: mysql:9.3.0   # 必须采用此版本
    container_name: emshop-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - emshop-mysql-data:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
      - ./mysql/conf:/etc/mysql/conf.d
    networks:
      - emshop-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s


  emshop-canal-server:
    image: canal/canal-server:v1.1.8
    container_name: emshop-canal-server
    restart: unless-stopped
    ports:
      - "11111:11111"
    volumes:
      # 启用配置文件挂载以覆盖Docker镜像默认配置
      - ./canal-server/logs:/home/admin/canal-server/logs
      - ./canal-server/conf:/home/admin/canal-server/conf
    depends_on:
      - emshop-mysql
    networks:
      - emshop-net

volumes:
  # MySQL 数据卷 - 使用外部卷
  emshop-mysql-data:
    name: emshop-mysql-data
    external: true

