services:
  emshop-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION:-8.11.0}
    container_name: emshop-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms${ES_HEAP_SIZE:-512m} -Xmx${ES_HEAP_SIZE:-512m}"
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    networks:
      - emshop-net
    ports:
      - "${ES_PORT:-9200}:9200"
      - "${ES_TRANSPORT_PORT:-9300}:9300"
    volumes:
      - emshop-elasticsearch-data:/usr/share/elasticsearch/data
      - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./logs/elasticsearch:/usr/share/elasticsearch/logs
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  emshop-kibana:
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION:-8.11.0}
    container_name: emshop-kibana
    restart: unless-stopped
    depends_on:
      emshop-elasticsearch:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_HOSTS=http://emshop-elasticsearch:9200
    networks:
      - emshop-net
    ports:
      - "${KIBANA_PORT:-5601}:5601"
    volumes:
      - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - ./logs/kibana:/usr/share/kibana/logs
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  emshop-logstash:
    image: docker.elastic.co/logstash/logstash:${ELK_VERSION:-8.11.0}
    container_name: emshop-logstash
    restart: unless-stopped
    depends_on:
      emshop-elasticsearch:
        condition: service_healthy
    environment:
      - "LS_JAVA_OPTS=-Xmx${LS_HEAP_SIZE:-256m} -Xms${LS_HEAP_SIZE:-256m}"
    networks:
      - emshop-net
    ports:
      - "${LOGSTASH_PORT:-5044}:5044"
      - "${LOGSTASH_TCP_PORT:-5000}:5000/tcp"
      - "${LOGSTASH_UDP_PORT:-5000}:5000/udp"
    volumes:
      - ./config/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./config/logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./logs/logstash:/usr/share/logstash/logs

volumes:
  emshop-elasticsearch-data:
    name: emshop-elasticsearch-data