
services:
  #Service for nameserver
  rmqnamesrv:
    image: apache/rocketmq:${ROCKETMQ_VERSION}
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./data/namesrv/logs:/home/rocketmq/logs
    networks:
      - emshop-net
    command: sh mqnamesrv

  #Service for broker
  rmqbroker:
    image: apache/rocketmq:${ROCKETMQ_VERSION}
    container_name: rmqbroker
    depends_on:
      - rmqnamesrv
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
    volumes:
      - ./data/broker/logs:/home/rocketmq/logs
      - emshop-rocketmq-broker-data:/home/rocketmq/store
      - ./data/broker/conf/broker.conf:/opt/rocketmq-${ROCKETMQ_VERSION}/conf/broker.conf
    networks:
      - emshop-net
    healthcheck:
      test: ["CMD-SHELL", "sh mqadmin clusterList -n rmqnamesrv:9876 | grep -q broker || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    command: sh mqbroker -c /opt/rocketmq-${ROCKETMQ_VERSION}/conf/broker.conf


  #Service for proxy
  rmqproxy:
    image: apache/rocketmq:${ROCKETMQ_VERSION}
    container_name: rmqproxy
    depends_on:
      rmqbroker:
        condition: service_healthy
    ports:
      - 18080:8080
      - 18081:8081
    restart: on-failure:3
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
      - JAVA_OPTS=-server -Xms512m -Xmx512m -Xmn256m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m
    volumes:
      - ./proxy/logs:/home/rocketmq/logs
      - ./proxy/conf/rmq-proxy.json:/opt/rocketmq-${ROCKETMQ_VERSION}/conf/rmq-proxy.json
    networks:
      - emshop-net
    healthcheck:
      test: ["CMD-SHELL", "netstat -tln | grep -E '8080|8081' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
    command: sh mqproxy -pc /opt/rocketmq-${ROCKETMQ_VERSION}/conf/rmq-proxy.json

  #Service for console (dashboard)
  rmqconsole:
    image: apacherocketmq/rocketmq-dashboard:1.0.0
    container_name: rmqconsole
    links:
      - rmqnamesrv
    ports:
      - 18082:8080
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=rmqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false -Dlogging.level.org.apache.rocketmq=ERROR
    networks:
      - emshop-net
    restart: on-failure

  # RocketMQ 数据卷
volumes:
  emshop-rocketmq-broker-data:
    name: emshop-rocketmq-broker-data
