// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package srv

import (
	"emshop/gin-micro/app"
	"emshop/internal/app/pkg/options"
	"emshop/internal/app/user/srv/controller/user"
	"emshop/internal/app/user/srv/data/v1"
	v1_2 "emshop/internal/app/user/srv/service/v1"
	"emshop/pkg/log"
)

// Injectors from wire.go:

// wire Injector
func initApp(nacosOptions *options.NacosOptions, logOptions *log.Options, serverOptions *options.ServerOptions, registryOptions *options.RegistryOptions, telemetryOptions *options.TelemetryOptions, mySQLOptions *options.MySQLOptions) (*app.App, error) {
	registrar := NewRegistrar(registryOptions, logOptions.Development)
	factoryManager, err := v1.NewFactoryManager(mySQLOptions)
	if err != nil {
		return nil, err
	}
	userSrv := v1_2.NewUserService(factoryManager)
	userServer := user.NewUserServer(userSrv)
	nacosDataSource, err := NewNacosDataSource(nacosOptions)
	if err != nil {
		return nil, err
	}
	server, err := NewUserRPCServer(telemetryOptions, serverOptions, userServer, nacosDataSource)
	if err != nil {
		return nil, err
	}
	appApp, err := NewUserApp(logOptions, registrar, serverOptions, server)
	if err != nil {
		return nil, err
	}
	return appApp, nil
}
