# ===============================================
# Goods Service 统一配置文件 - 包含Canal + RocketMQ集成
# 整合自: srv.yaml, goods-canal.yaml, goods-service-with-canal.yaml
# ===============================================

# 服务器配置
server:
  name: "goods" # 服务名，注册到consul使用的名称，与Canal配置保持一致
  host: "0.0.0.0" # host, 默认使用 0.0.0.0,docker容器中不能使用127.0.0.1
  port: 9002 # grpc端口，使用Canal配置的端口保持一致性
  http-port: 8053 # HTTP端口
  healthz: true # 是否开启健康检查，如果开启会安装 /healthz 路由，默认 true
  enable-metrics: true # 开启 metrics, router:  /metrics  
  profiling: true # 开启性能分析, 可以通过 <host>:<port>/debug/pprof/地址查看程序栈、线程等系统信息，默认值为 true

# 日志配置
log:
  name: emshop-goods-srv # logger的名称
  development: true # 是否开启开发模式，开发模式下会打印调试信息，默认 false
  level: debug # 日志级别，优先级从低到高依次为：debug, info, warn, error, dpanic, panic, fatal。
  format: json # 支持的日志输出格式，Canal集成使用json格式便于日志分析
  enable-color: false # JSON格式下关闭颜色输出
  disable-caller: false # 是否开启 caller，如果开启会在日志中显示调用日志所在的文件、函数和行号
  disable-stacktrace: false # 是否再panic及以上级别禁止打印堆栈信息
  output-paths: logs/emshop-goods-srv.log,stdout # 支持输出到多个输出，逗号分开。支持输出到标准输出（stdout）和文件。
  error-output-paths: logs/emshop-goods-srv.error.log # zap内部(非业务)错误日志输出路径，多个输出，逗号分开

# 服务注册与发现配置
registry:
  address: localhost:8500 # Consul地址，与测试环境保持一致
  scheme: http

# 链路追踪配置
telemetry:
  name: goods # 服务名称，与server.name保持一致
  endpoint: http://localhost:14268/api/traces # Jaeger端点
  sampler: 1.0 # 采样率
  batcher: jaeger # 批处理器

# MySQL 数据库相关配置
mysql:
  host: "localhost" # MySQL 机器 ip，与Canal测试环境保持一致
  port: 3306 # 端口号统一为数值类型
  password: "root" # MySQL 用户密码
  username: "root" # MySQL 用户名(建议授权最小权限集)
  database: "emshop_goods_srv" # 商品服务数据库名
  max_idle_connections: 10 # MySQL 最大空闲连接数，Canal配置优化值
  max_open_connections: 100 # MySQL 最大打开的连接数
  max_connection_life_time: "1h" # 空闲连接最大存活时间，Canal配置优化值
  log_level: 4 # GORM log level, 1: silent, 2:error, 3:warn, 4:info

# Elasticsearch配置 - 整合详细配置
es:
  host: "localhost" # Elasticsearch 地址，与测试环境保持一致
  port: 9200 # ES端口
  username: "" # ES用户名
  password: "" # ES密码  
  index_prefix: "" # 索引前缀
  addresses: # 支持多节点配置
    - "http://localhost:9200"
  enable_sniff: false # 关闭节点嗅探
  health_check_timeout: "5s" # 健康检查超时
  enable_gzip_compression: true # 启用gzip压缩

# ===============================================
# Canal + RocketMQ 数据同步配置
# ===============================================
rocketmq:
  nameservers: ["rmqnamesrv:9876"] # RocketMQ NameServer地址列表，与测试环境保持一致
  consumer_group: "goods-sync-consumer-group" # 消费者组名
  topic: "goods-binlog-topic" # Canal发送消息的主题，需要与Canal Server配置保持一致
  max_reconsume: 3 # 最大重试消费次数