global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s

  # Docker containers metrics (if you have cadvisor)
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:8080']
    scrape_interval: 10s
    metrics_path: '/metrics'

  # Add your application metrics here
  - job_name: 'emshop-api'
    static_configs:
      - targets: ['host.docker.internal:8051']
    scrape_interval: 5s
    metrics_path: '/metrics'
